---
title: "Reproducible Research Project1"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data
```{r}
library(lubridate)
library(ggplot2)
activity <- read.csv("activity.csv")
dim(activity)
head(activity)
names(activity)
str(activity)
length(unique(activity$date))
```

## What is mean total number of steps taken per day?

```{r}
activity_total_steps <- with(activity, aggregate(steps, by= list(date), FUN = sum, na.rm = TRUE))
names(activity_total_steps) <- c("date", "steps")
hist(activity_total_steps$steps, main = "Total number of steps per day", xlab = "Number of steps", col = "red", ylim = c(0, 20))
png("plot1.png")
mean(activity_total_steps$steps)
median(activity_total_steps$steps)
```

##What is the average daily pattern
```{r}
average_daily_activity <- aggregate(activity$steps, by=list(activity$interval), FUN = mean, na.rm = TRUE)
names(average_daily_activity) <- c("interval", "mean")
plot(average_daily_activity$interval, average_daily_activity$mean, type = "l", col = "red", lwd = 2, xlab = "Interval", ylab = "Number of steps", main = "Average Number of Steps per Interval")
average_daily_activity[which.max(average_daily_activity$mean),]$interval
```

##Imputing Missing Values
```{r}
sum(is.na(activity$steps))
imputed_steps <- average_daily_activity$mean [match(activity$interval, average_daily_activity$interval)]
activity_imputed <- transform(activity, steps = ifelse(is.na(activity$steps), yes = imputed_steps, no = activity$steps))
total_steps_imputed <- aggregate(steps ~ date, activity_imputed, sum)
names(total_steps_imputed) <- c("date", "daily_steps")
hist(total_steps_imputed$daily_steps, col = "red", xlab = "Number of Steps per Day", ylim = c(0, 30), main = "Total Number of Steps per Day")
mean(total_steps_imputed$daily_steps)
median(total_steps_imputed$daily_steps)
```

##Are there differences in activity patterns between weekdays and weekends?
```{r}
activity$date <- as.Date(strptime(activity$date, format = "%Y-%m-%d"))
activity$datetype <- sapply(activity$date, function(x) {
  if(weekdays(x) == "Saturday" | weekdays(x) == "Sunday")
  {y <- "Weekend"} else {y <- "Weekday"} 
  y
})
activity_by_date <- aggregate(steps~interval + datetype, activity, mean, type = "l", na.rm = TRUE)
plot<- ggplot(activity_by_date, aes(x = interval , y = steps, color = datetype)) +
  geom_line() +
  labs(title = "Average daily steps by type of date", x = "Interval", y = "Average number of steps") +
  facet_wrap(~datetype, ncol = 1, nrow=2)
print(plot)
```
